/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// Description
    /// </summary>
    public class GetTrackingsOptions : BaseOptions
    {
        public  GetTrackingsOptions()
        {
        }

        public string? Cursor { get; set; }
        public int? Limit { get; set; }
        public string? Keyword { get; set; }
        public string? TrackingNumbers { get; set; }
        public string? Slug { get; set; }
        public int? TransitTime { get; set; }
        public string? Origin { get; set; }
        public string? Destination { get; set; }
        public string? Tag { get; set; }
        public string? CreatedAtMin { get; set; }
        public string? CreatedAtMax { get; set; }
        public string? UpdatedAtMin { get; set; }
        public string? UpdatedAtMax { get; set; }
        public string? Fields { get; set; }
        public string? ReturnToSender { get; set; }
        public string? CourierDestinationCountryRegion { get; set; }
        public string? ShipmentTags { get; set; }
        public string? OrderId { get; set; }

        override public List<KeyValuePair<string, string>> GetQueryParams()
        {
            var p = new List<KeyValuePair<string, string>>();
            if (Cursor != null) {
                p.Add(new KeyValuePair<string, string>("cursor", Cursor));
            }
            if (Limit != null) {
                p.Add(new KeyValuePair<string, string>("limit", Limit.ToString()));
            }
            if (Keyword != null) {
                p.Add(new KeyValuePair<string, string>("keyword", Keyword));
            }
            if (TrackingNumbers != null) {
                p.Add(new KeyValuePair<string, string>("tracking_numbers", TrackingNumbers));
            }
            if (Slug != null) {
                p.Add(new KeyValuePair<string, string>("slug", Slug));
            }
            if (TransitTime != null) {
                p.Add(new KeyValuePair<string, string>("transit_time", TransitTime.ToString()));
            }
            if (Origin != null) {
                p.Add(new KeyValuePair<string, string>("origin", Origin));
            }
            if (Destination != null) {
                p.Add(new KeyValuePair<string, string>("destination", Destination));
            }
            if (Tag != null) {
                p.Add(new KeyValuePair<string, string>("tag", Tag));
            }
            if (CreatedAtMin != null) {
                p.Add(new KeyValuePair<string, string>("created_at_min", CreatedAtMin));
            }
            if (CreatedAtMax != null) {
                p.Add(new KeyValuePair<string, string>("created_at_max", CreatedAtMax));
            }
            if (UpdatedAtMin != null) {
                p.Add(new KeyValuePair<string, string>("updated_at_min", UpdatedAtMin));
            }
            if (UpdatedAtMax != null) {
                p.Add(new KeyValuePair<string, string>("updated_at_max", UpdatedAtMax));
            }
            if (Fields != null) {
                p.Add(new KeyValuePair<string, string>("fields", Fields));
            }
            if (ReturnToSender != null) {
                p.Add(new KeyValuePair<string, string>("return_to_sender", ReturnToSender));
            }
            if (CourierDestinationCountryRegion != null) {
                p.Add(new KeyValuePair<string, string>("courier_destination_country_region", CourierDestinationCountryRegion));
            }
            if (ShipmentTags != null) {
                p.Add(new KeyValuePair<string, string>("shipment_tags", ShipmentTags));
            }
            if (OrderId != null) {
                p.Add(new KeyValuePair<string, string>("order_id", OrderId));
            }
            return p;
        }
    }
    /// <summary>
    /// Description
    /// </summary>
    public class CreateTrackingOptions : BaseOptions
    {
        public  CreateTrackingOptions()
        {
        }


        public CreateTrackingRequest CreateTrackingRequest { get; set; }

        override public string GetBody()
        {
            string body = null;

            if ( CreateTrackingRequest != null)
            {
                body = BaseResourceService.ToJson(CreateTrackingRequest);
            }
            return body;
        }
    }
    /// <summary>
    /// Description
    /// </summary>
    public class GetTrackingByIdOptions : BaseOptions
    {
        public  GetTrackingByIdOptions()
        {
        }

        public string? Fields { get; set; }
        public string? Lang { get; set; }

        override public List<KeyValuePair<string, string>> GetQueryParams()
        {
            var p = new List<KeyValuePair<string, string>>();
            if (Fields != null) {
                p.Add(new KeyValuePair<string, string>("fields", Fields));
            }
            if (Lang != null) {
                p.Add(new KeyValuePair<string, string>("lang", Lang));
            }
            return p;
        }
    }
    /// <summary>
    /// Description
    /// </summary>
    public class UpdateTrackingByIdOptions : BaseOptions
    {
        public  UpdateTrackingByIdOptions()
        {
        }


        public UpdateTrackingByIdRequest UpdateTrackingByIdRequest { get; set; }

        override public string GetBody()
        {
            string body = null;

            if ( UpdateTrackingByIdRequest != null)
            {
                body = BaseResourceService.ToJson(UpdateTrackingByIdRequest);
            }
            return body;
        }
    }
    /// <summary>
    /// Description
    /// </summary>
    public class DeleteTrackingByIdOptions : BaseOptions
    {
        public  DeleteTrackingByIdOptions()
        {
        }


    }
    /// <summary>
    /// Description
    /// </summary>
    public class RetrackTrackingByIdOptions : BaseOptions
    {
        public  RetrackTrackingByIdOptions()
        {
        }


    }
    /// <summary>
    /// Description
    /// </summary>
    public class MarkTrackingCompletedByIdOptions : BaseOptions
    {
        public  MarkTrackingCompletedByIdOptions()
        {
        }


        public MarkTrackingCompletedByIdRequest MarkTrackingCompletedByIdRequest { get; set; }

        override public string GetBody()
        {
            string body = null;

            if ( MarkTrackingCompletedByIdRequest != null)
            {
                body = BaseResourceService.ToJson(MarkTrackingCompletedByIdRequest);
            }
            return body;
        }
    }
}
