/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Net.Http;

namespace AfterShipTracking
{
    public class TrackingService : BaseResourceService
    {
        IHttpClient HttpClient;

        public TrackingService(IHttpClient httpClient)
        {
            this.HttpClient = httpClient;
        }

        public GetTrackingsResponse GetTrackings( GetTrackingsOptions? options = null)
        {
            string path = $"/tracking/2026-07/trackings";
            Request request = new Request(
                HttpMethod.Get,
                path,
                options
            );

            var response = this.HttpClient.MakeRequest(request);
            GetTrackingsResponseData responseData = ProcessData<GetTrackingsResponseData>(response);

            GetTrackingsResponse result = new GetTrackingsResponse();
            result.ResponseHeader = response.Headers;
            result.Data = responseData;

            return result;
        }
        public CreateTrackingResponse CreateTracking( CreateTrackingOptions? options = null)
        {
            string path = $"/tracking/2026-07/trackings";
            Request request = new Request(
                HttpMethod.Post,
                path,
                options
            );

            var response = this.HttpClient.MakeRequest(request);
            Tracking responseData = ProcessData<Tracking>(response);

            CreateTrackingResponse result = new CreateTrackingResponse();
            result.ResponseHeader = response.Headers;
            result.Data = responseData;

            return result;
        }
        public GetTrackingByIdResponse GetTrackingById(string id,  GetTrackingByIdOptions? options = null)
        {
            string path = $"/tracking/2026-07/trackings/{id}";
            if (string.IsNullOrEmpty(id))
            {
               throw ErrorCode.GenSDKError(ErrorCode.BAD_REQUEST, "Invalid request"+": `id` is invalid");
            }
            Request request = new Request(
                HttpMethod.Get,
                path,
                options
            );

            var response = this.HttpClient.MakeRequest(request);
            Tracking responseData = ProcessData<Tracking>(response);

            GetTrackingByIdResponse result = new GetTrackingByIdResponse();
            result.ResponseHeader = response.Headers;
            result.Data = responseData;

            return result;
        }
        public UpdateTrackingByIdResponse UpdateTrackingById(string id,  UpdateTrackingByIdOptions? options = null)
        {
            string path = $"/tracking/2026-07/trackings/{id}";
            if (string.IsNullOrEmpty(id))
            {
               throw ErrorCode.GenSDKError(ErrorCode.BAD_REQUEST, "Invalid request"+": `id` is invalid");
            }
            Request request = new Request(
                HttpMethod.Put,
                path,
                options
            );

            var response = this.HttpClient.MakeRequest(request);
            Tracking responseData = ProcessData<Tracking>(response);

            UpdateTrackingByIdResponse result = new UpdateTrackingByIdResponse();
            result.ResponseHeader = response.Headers;
            result.Data = responseData;

            return result;
        }
        public DeleteTrackingByIdResponse DeleteTrackingById(string id,  DeleteTrackingByIdOptions? options = null)
        {
            string path = $"/tracking/2026-07/trackings/{id}";
            if (string.IsNullOrEmpty(id))
            {
               throw ErrorCode.GenSDKError(ErrorCode.BAD_REQUEST, "Invalid request"+": `id` is invalid");
            }
            Request request = new Request(
                HttpMethod.Delete,
                path,
                options
            );

            var response = this.HttpClient.MakeRequest(request);
            Tracking responseData = ProcessData<Tracking>(response);

            DeleteTrackingByIdResponse result = new DeleteTrackingByIdResponse();
            result.ResponseHeader = response.Headers;
            result.Data = responseData;

            return result;
        }
        public RetrackTrackingByIdResponse RetrackTrackingById(string id,  RetrackTrackingByIdOptions? options = null)
        {
            string path = $"/tracking/2026-07/trackings/{id}/retrack";
            if (string.IsNullOrEmpty(id))
            {
               throw ErrorCode.GenSDKError(ErrorCode.BAD_REQUEST, "Invalid request"+": `id` is invalid");
            }
            Request request = new Request(
                HttpMethod.Post,
                path,
                options
            );

            var response = this.HttpClient.MakeRequest(request);
            Tracking responseData = ProcessData<Tracking>(response);

            RetrackTrackingByIdResponse result = new RetrackTrackingByIdResponse();
            result.ResponseHeader = response.Headers;
            result.Data = responseData;

            return result;
        }
        public MarkTrackingCompletedByIdResponse MarkTrackingCompletedById(string id,  MarkTrackingCompletedByIdOptions? options = null)
        {
            string path = $"/tracking/2026-07/trackings/{id}/mark-as-completed";
            if (string.IsNullOrEmpty(id))
            {
               throw ErrorCode.GenSDKError(ErrorCode.BAD_REQUEST, "Invalid request"+": `id` is invalid");
            }
            Request request = new Request(
                HttpMethod.Post,
                path,
                options
            );

            var response = this.HttpClient.MakeRequest(request);
            Tracking responseData = ProcessData<Tracking>(response);

            MarkTrackingCompletedByIdResponse result = new MarkTrackingCompletedByIdResponse();
            result.ResponseHeader = response.Headers;
            result.Data = responseData;

            return result;
        }
    }
}

