/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace AfterShipTracking
{
    /// <summary>
    /// The source of the checkpoint, which can either be from the carrier or when the user marks the tracking as completed.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CheckpointSource
    {
        [EnumMember(Value = "carrier")]
        Carrier,
        [EnumMember(Value = "user")]
        User,
    }
}
