/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// 
    /// </summary>
    public class CheckpointEvents
    {
        /// <summary>
        ///  Code Represents the event code.
        /// </summary>
        [JsonProperty("code")]
        public string Code { get; set; }
        /// <summary>
        ///  Reason Describes the specific reason that led to the event.
        /// </summary>
        [JsonProperty("reason")]
        public CheckpointEventsReason? Reason { get; set; }
        public CheckpointEvents()
        {
        }
    }
}
