/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// Describes the specific reason that led to the event.
    /// </summary>
    public class CheckpointEventsReason
    {
        /// <summary>
        ///  Code The code of the reason. 
        /// </summary>
        [JsonProperty("code")]
        public string Code { get; set; }
        public CheckpointEventsReason()
        {
        }
    }
}
