/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// 
    /// </summary>
    public class CourierConnectionResponseForGetCourierConnectionsData
    {
        /// <summary>
        ///  Pagination 
        /// </summary>
        [JsonProperty("pagination")]
        public CourierConnectionResponseForGetCourierConnectionsDataPagination Pagination { get; set; }
        /// <summary>
        ///  CourierConnections 
        /// </summary>
        [JsonProperty("courier_connections")]
        public CourierConnection[]? CourierConnections { get; set; }
        public CourierConnectionResponseForGetCourierConnectionsData()
        {
        }
    }
}
