/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// This model represents user-created courier connection details. AfterShip will use this information to retrieve tracking updates from carriers based on the provided tracking numbers.
    /// </summary>
    public class  CourierConnection
    {
        /// <summary>
        ///  Id The courier connection ID is a special set of numbers generated by AfterShip to define each user-created connection.
        /// </summary>
        [JsonProperty("id")]
        public string  Id { get; set; }
        /// <summary>
        ///  CourierSlug Unique courier code. Get courier codes .
        /// </summary>
        [JsonProperty("courier_slug")]
        public string  CourierSlug { get; set; }
        /// <summary>
        ///  Credentials It refers to the authentication details required for each specific carrier details required for each specific carrier (such as API keys, username, password, etc.) that the user must provide to establish a carrier connection. The content varies by carrier.
        /// </summary>
        [JsonProperty("credentials")]
        public Dictionary<string, string>  Credentials { get; set; }
        /// <summary>
        ///  CreatedAt The date and time the courier connection was created. It uses the format YYYY-MM-DDTHH:mm:ssZ for the timezone GMT +0.
        /// </summary>
        [JsonProperty("created_at")]
        public string  CreatedAt { get; set; }
        /// <summary>
        ///  UpdatedAt The date and time the courier connection was updated. It uses the format YYYY-MM-DDTHH:mm:ssZ for the timezone GMT +0.
        /// </summary>
        [JsonProperty("updated_at")]
        public string  UpdatedAt { get; set; }
        public CourierConnection()
        {
        }
    }
}
