/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// Model of all couriers endpoint response
    /// </summary>
    public class CourierResponse
    {
        /// <summary>
        ///  Meta Meta data
        /// </summary>
        [JsonProperty("meta")]
        public Meta Meta { get; set; }
        /// <summary>
        ///  Data 
        /// </summary>
        [JsonProperty("data")]
        public CourierResponseData Data { get; set; }
        public CourierResponse()
        {
        }
    }
}
