/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// This field contains information about the last leg of the shipment, starting from the carrier who hands it over to the last-mile carrier, all the way to delivery. Once AfterShip detects that the shipment involves multiple legs and identifies the last-mile carrier, we will populate the last-mile carrier information in this object. Alternatively, the user can provide this information in this field to specify the last-mile carrier, which is helpful if AfterShip is unable to detect it automatically.
    /// </summary>
    public class CreateTrackingRequestLastMile
    {
        /// <summary>
        ///  TrackingNumber The tracking number of the last-mile carrier.
        /// </summary>
        [JsonProperty("tracking_number")]
        public string TrackingNumber { get; set; }
        /// <summary>
        ///  Slug The unique code of the carrier responsible for the last-mile of the shipment.  Find all the courier slugs .
        /// </summary>
        [JsonProperty("slug")]
        public string Slug { get; set; }
        public CreateTrackingRequestLastMile()
        {
        }
    }
}
