/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace AfterShipTracking
{
    /// <summary>
    /// Shipment delivery type- pickup_at_store- pickup_at_courier- door_to_door
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CreateTrackingRequestDeliveryType
    {
        [EnumMember(Value = "pickup_at_store")]
        PickupAtStore,
        [EnumMember(Value = "door_to_door")]
        DoorToDoor,
        [EnumMember(Value = "pickup_at_courier")]
        PickupAtCourier,
    }
}
