/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// 
    /// </summary>
    public class  CredentialField
    {
        /// <summary>
        ///  Name The display name of the credential field that users must provide when creating a carrier connection.
        /// </summary>
        [JsonProperty("name")]
        public string  Name { get; set; }
        /// <summary>
        ///  Type The data type of the credential field, indicating what kind of input is expected.
        /// </summary>
        [JsonProperty("type")]
        public string  Type { get; set; }
        /// <summary>
        ///  Required It indicates whether the credentials field must be provided or not when creating a carrier connection.
        /// </summary>
        [JsonProperty("required")]
        public bool  Required { get; set; }
        public CredentialField()
        {
        }
    }
}
