/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Headers = System.Net.Http.Headers.HttpResponseHeaders;

namespace AfterShipTracking
{
    public class  DetectCourierResponse
    {
        public Headers ResponseHeader { get; set; }
        public DetectCourierResponseData Data { get; set; }
        public DetectCourierResponse()
        {
        }
    }
}
