/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// 
    /// </summary>
    public class EstimatedDeliveryDateRequestEstimatedPickupOrderProcessingTime
    {
        /// <summary>
        ///  Unit Processing time of an order, from being placed to being picked up. Only support day as value now.AfterShip will set day as the default value.
        /// </summary>
        [JsonProperty("unit")]
        public string Unit { get; set; }
        /// <summary>
        ///  Value Processing time of an order, from being placed to being picked up.AfterShip will set 0 as the default value.
        /// </summary>
        [JsonProperty("value")]
        public double Value { get; set; }
        public EstimatedDeliveryDateRequestEstimatedPickupOrderProcessingTime()
        {
        }
    }
}
