/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// AfterShip uses this object to calculate the total weight of the order.
    /// </summary>
    public class  EstimatedDeliveryDateResponseWeight
    {
        /// <summary>
        ///  Unit The weight unit of the package. 
        /// </summary>
        [JsonProperty("unit")]
        public string  Unit { get; set; }
        /// <summary>
        ///  Value The weight of the shipment.
        /// </summary>
        [JsonProperty("value")]
        public double  Value { get; set; }
        public EstimatedDeliveryDateResponseWeight()
        {
        }
    }
}
