/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// 
    /// </summary>
    public class EstimatedDeliveryDateResponse
    {
        /// <summary>
        ///  Id A string that acts as a unique identifier for the estimated delivery date value generated by AfterShip Predict API
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; }
        /// <summary>
        ///  Slug AfterShip's unique code of courier. Please refer to https://track.aftership.com/couriers/download.
        /// </summary>
        [JsonProperty("slug")]
        public string Slug { get; set; }
        /// <summary>
        ///  ServiceTypeName AfterShip’s unique code represents carrier’s shipping and delivery options. Refer to .
        /// </summary>
        [JsonProperty("service_type_name")]
        public string? ServiceTypeName { get; set; }
        /// <summary>
        ///  OriginAddress The location from where the package is picked up by the carrier to be delivered to the final destination.
        /// </summary>
        [JsonProperty("origin_address")]
        public EstimatedDeliveryDateResponseOriginAddress OriginAddress { get; set; }
        /// <summary>
        ///  DestinationAddress The final destination of the customer where the delivery will be made.
        /// </summary>
        [JsonProperty("destination_address")]
        public EstimatedDeliveryDateResponseDestinationAddress DestinationAddress { get; set; }
        /// <summary>
        ///  Weight AfterShip uses this object to calculate the total weight of the order.
        /// </summary>
        [JsonProperty("weight")]
        public EstimatedDeliveryDateResponseWeight? Weight { get; set; }
        /// <summary>
        ///  PackageCount The number of packages.
        /// </summary>
        [JsonProperty("package_count")]
        public int? PackageCount { get; set; }
        /// <summary>
        ///  PickupTime The local pickup time in the origin address time zone of the package.Either `pickup_time` or `estimated_pickup` is required.
        /// </summary>
        [JsonProperty("pickup_time")]
        public string? PickupTime { get; set; }
        /// <summary>
        ///  EstimatedPickup The local pickup time of the package.Either `pickup_time` or `estimated_pickup` is required.
        /// </summary>
        [JsonProperty("estimated_pickup")]
        public EstimatedDeliveryDateResponseEstimatedPickup? EstimatedPickup { get; set; }
        /// <summary>
        ///  EstimatedDeliveryDate The estimated arrival date of the shipment, provided by AfterShip.
        /// </summary>
        [JsonProperty("estimated_delivery_date")]
        public string EstimatedDeliveryDate { get; set; }
        /// <summary>
        ///  ConfidenceCode Indicates the confidence level and associated reason for an AI EDD prediction request. For a comprehensive list of confidence codes, refer to .
        /// </summary>
        [JsonProperty("confidence_code")]
        public double ConfidenceCode { get; set; }
        /// <summary>
        ///  EstimatedDeliveryDateMin The earliest estimated delivery date of the shipment, provided by AfterShip.
        /// </summary>
        [JsonProperty("estimated_delivery_date_min")]
        public string EstimatedDeliveryDateMin { get; set; }
        /// <summary>
        ///  EstimatedDeliveryDateMax The latest estimated delivery date of the shipment, provided by AfterShip.
        /// </summary>
        [JsonProperty("estimated_delivery_date_max")]
        public string EstimatedDeliveryDateMax { get; set; }
        public EstimatedDeliveryDateResponse()
        {
        }
    }
}
