/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// 
    /// </summary>
    public class  GetTrackingsResponseData
    {
        /// <summary>
        ///  Pagination The Pagination holds the information for the pagination when the response contains multiple objects.
        /// </summary>
        [JsonProperty("pagination")]
        public GetTrackingsResponseDataPagination  Pagination { get; set; }
        /// <summary>
        ///  Trackings Array of 
        /// </summary>
        [JsonProperty("trackings")]
        public Tracking []? Trackings { get; set; }
        public GetTrackingsResponseData()
        {
        }
    }
}
