/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace AfterShipTracking
{
    /// <summary>
    /// error type, only exist if the response status is not 2xx
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum MetaType
    {
        [EnumMember(Value = "BadRequest")]
        BadRequest,
        [EnumMember(Value = "Unauthorized")]
        Unauthorized,
        [EnumMember(Value = "Forbidden")]
        Forbidden,
        [EnumMember(Value = "NotFound")]
        NotFound,
        [EnumMember(Value = "TooManyRequests")]
        TooManyRequests,
        [EnumMember(Value = "InternalError")]
        InternalError,
    }
}
