/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// 
    /// </summary>
    public class  PutCourierConnectionsByIdRequest
    {
        /// <summary>
        ///  Credentials It refers to the authentication details required for each specific carrier details required for each specific carrier (such as API keys, username, password, etc.) that the user must provide to establish a carrier connection. The content varies by carrier.
        /// </summary>
        [JsonProperty("credentials")]
        public Dictionary<string, string>  Credentials { get; set; }
        public PutCourierConnectionsByIdRequest()
        {
        }
    }
}
