/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace AfterShipTracking
{
    /// <summary>
    /// Indicates the role of the current tracking object within the multi-piece shipment.Possible values:- `master`: The main tracking number representing the entire shipment. It may not always exist.- `child`: A sub-tracking number belonging to one of the pieces in the shipment.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TrackingMultiPieceInfoType
    {
        [EnumMember(Value = "master")]
        Master,
        [EnumMember(Value = "child")]
        Child,
    }
}
