/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// 
    /// </summary>
    public class  TrackingProofOfDelivery
    {
        /// <summary>
        ///  Type The file type of the proof of delivery record. Currently, only images are supported.
        /// </summary>
        [JsonProperty("type")]
        public string  Type { get; set; }
        /// <summary>
        ///  Url The URL of the proof of delivery record.
        /// </summary>
        [JsonProperty("url")]
        public string  Url { get; set; }
        public TrackingProofOfDelivery()
        {
        }
    }
}
