/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace AfterShipTracking
{
    /// <summary>
    /// The signature_requirement field serves the purpose of validating the service option type, specifically proof of delivery. By collecting the recipient&#39;s signature upon delivery, it ensures the package reaches the intended recipient and prevents disputes related to non-delivery or lost packages.&lt;/br&gt;
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TrackingSignatureRequirement
    {
        [EnumMember(Value = "signature_required")]
        SignatureRequired,
        [EnumMember(Value = "adult_signature_required")]
        AdultSignatureRequired,
        [EnumMember(Value = "indirect_signature_required")]
        IndirectSignatureRequired,
        [EnumMember(Value = "no_signature_required")]
        NoSignatureRequired,
        [EnumMember(Value = "null")]
        Null,
    }
}
