/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// Tracking response for getting tracking
    /// </summary>
    public class  TrackingResponseForGetTrackings
    {
        /// <summary>
        ///  Meta Meta data
        /// </summary>
        [JsonProperty("meta")]
        public Meta  Meta { get; set; }
        /// <summary>
        ///  Data 
        /// </summary>
        [JsonProperty("data")]
        public TrackingResponseForGetTrackingsData  Data { get; set; }
        public TrackingResponseForGetTrackings()
        {
        }
    }
}
