/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace AfterShipTracking
{
    /// <summary>
    /// Type of the piece within the MPS: `master` or `child`.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TrackingMultiPieceInfoPiecesType
    {
        [EnumMember(Value = "master")]
        Master,
        [EnumMember(Value = "child")]
        Child,
    }
}
