/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace AfterShipTracking
{
    /// <summary>
    /// The field indicates the source of last-mile carrier.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TrackingLastMileSource
    {
        [EnumMember(Value = "system")]
        System,
        [EnumMember(Value = "user")]
        User,
    }
}
