/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// The Pagination holds the information for the pagination when the response contains multiple objects.
    /// </summary>
    public class TrackingResponseForGetTrackingsDataPagination
    {
        /// <summary>
        ///  Total The total number of trackings.
        /// </summary>
        [JsonProperty("total")]
        public int Total { get; set; }
        /// <summary>
        ///  NextCursor A string representing the cursor value for the next page of results.
        /// </summary>
        [JsonProperty("next_cursor")]
        public string NextCursor { get; set; }
        /// <summary>
        ///  HasNextPage To indicate if next page is available.
        /// </summary>
        [JsonProperty("has_next_page")]
        public bool HasNextPage { get; set; }
        public TrackingResponseForGetTrackingsDataPagination()
        {
        }
    }
}
