/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// The field contains the estimated delivery date provided by the carrier.
    /// </summary>
    public class TrackingCourierEstimatedDeliveryDate
    {
        /// <summary>
        ///  EstimatedDeliveryDate The estimated arrival date of the shipment. It reflects the shipment recipient’s timezone and the format may vary based on how the carrier provides it:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
        /// </summary>
        [JsonProperty("estimated_delivery_date")]
        public string? EstimatedDeliveryDate { get; set; }
        /// <summary>
        ///  EstimatedDeliveryDateMin The earliest estimated delivery date of the shipment. It reflects the shipment recipient’s timezone and the format may vary based on how the carrier provides it:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
        /// </summary>
        [JsonProperty("estimated_delivery_date_min")]
        public string? EstimatedDeliveryDateMin { get; set; }
        /// <summary>
        ///  EstimatedDeliveryDateMax The Latest estimated delivery date of the shipment. It reflects the shipment recipient’s timezone and the format may vary based on how the carrier provides it:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
        /// </summary>
        [JsonProperty("estimated_delivery_date_max")]
        public string? EstimatedDeliveryDateMax { get; set; }
        public TrackingCourierEstimatedDeliveryDate()
        {
        }
    }
}
