/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// The field contains information about the first leg of the shipping starting from the carrier picking up the shipment from the shipper to the point where they hand it over to the last-mile carrier. Once AfterShip detects the shipment is multi-leg, we will populate the first-mile information under this object. 
    /// </summary>
    public class TrackingFirstMile
    {
        /// <summary>
        ///  TrackingNumber The tracking number of the first-mile carrier.
        /// </summary>
        [JsonProperty("tracking_number")]
        public string TrackingNumber { get; set; }
        /// <summary>
        ///  Slug The unique code of the carrier responsible for the first-mile of the shipment. Find all the courier slugs .
        /// </summary>
        [JsonProperty("slug")]
        public string Slug { get; set; }
        /// <summary>
        ///  TransitTime The transit time for the first-mile of a shipment in days. This field is calculated based on whether the handed_over_to_last_mile_carrier or received_by_last_mile_carrier event is detected by AfterShip. The handover event date is used to calculate the first-mile transit time.- First mile transit time (in days) = Handover date - Pickup date 
        /// </summary>
        [JsonProperty("transit_time")]
        public int? TransitTime { get; set; }
        /// <summary>
        ///  CourierRedirectLink The field provides the link for modifying delivery instructions (such as delivery date and shipping address), if supported by the first-mile carrier. The language parameter of this link is determined by the destination country/region and the language associated with the shipment. If the destination country/region and language data is unavailable, AfterShip will default the language parameter to "US".
        /// </summary>
        [JsonProperty("courier_redirect_link")]
        public string? CourierRedirectLink { get; set; }
        /// <summary>
        ///  CourierTrackingLink The field contains the official tracking URL of the first-mile carrier, if available. The language parameter of this link is determined by the destination country/region and the language associated with the shipment. If the destination country/region and language data is unavailable, AfterShip will default the language parameter to "US".
        /// </summary>
        [JsonProperty("courier_tracking_link")]
        public string? CourierTrackingLink { get; set; }
        public TrackingFirstMile()
        {
        }
    }
}
