/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace AfterShipTracking
{
    /// <summary>
    /// The source of the EDD. Either the carrier, AfterShip AI, or based on your custom EDD settings.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TrackingFirstEstimatedDeliverySource
    {
        [EnumMember(Value = "Carrier EDD")]
        CarrierEdd,
        [EnumMember(Value = "AfterShip EDD")]
        AfterShipEdd,
        [EnumMember(Value = "Custom EDD")]
        CustomEdd,
        [EnumMember(Value = "Order EDD")]
        OrderEdd,
    }
}
