/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// 
    /// </summary>
    public class  TrackingMultiPieceInfoPieces
    {
        /// <summary>
        ///  TrackingId AfterShip system-assigned unique identifier for the piece.
        /// </summary>
        [JsonProperty("tracking_id")]
        public string  TrackingId { get; set; }
        /// <summary>
        ///  TrackingNumber Carrier-assigned tracking number for the piece.
        /// </summary>
        [JsonProperty("tracking_number")]
        public string  TrackingNumber { get; set; }
        /// <summary>
        ///  Type Type of the piece within the MPS: `master` or `child`.
        /// </summary>
        [JsonProperty("type")]
        public TrackingMultiPieceInfoPiecesType?  Type { get; set; }
        /// <summary>
        ///  Trackable Indicates whether the tracking number can be used to retrieve tracking updates on the carrier's side. If not, it means the carrier can only return a child tracking number, but cannot independently provide tracking updates for the sub-shipment. In this case, it is not recommended for you to import this tracking number into AfterShip for tracking.
        /// </summary>
        [JsonProperty("trackable")]
        public bool  Trackable { get; set; }
        public TrackingMultiPieceInfoPieces()
        {
        }
    }
}
