/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace AfterShipTracking
{
    /// <summary>
    /// The format of the EDD. Either a single date or a date range.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TrackingFirstEstimatedDeliveryType
    {
        [EnumMember(Value = "range")]
        Range,
        [EnumMember(Value = "specific")]
        Specific,
    }
}
