/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// The most recently calculated estimated delivery date. It could be provided by the carrier, AfterShip AI, or based on your custom settings. The format of carrier EDDs may differ depending on how the carrier provides it:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ AfterShip AI and custom EDDs always use the format `YYYY-MM-DD`. All EDDs use the shipment recipient’s timezone.
    /// </summary>
    public class  TrackingLatestEstimatedDelivery
    {
        /// <summary>
        ///  Type The format of the EDD. Either a single date or a date range.
        /// </summary>
        [JsonProperty("type")]
        public TrackingLatestEstimatedDeliveryType?  Type { get; set; }
        /// <summary>
        ///  Source The source of the EDD. Either the carrier, AfterShip AI, or based on your custom EDD settings.
        /// </summary>
        [JsonProperty("source")]
        public TrackingLatestEstimatedDeliverySource?  Source { get; set; }
        /// <summary>
        ///  Datetime The latest EDD time.
        /// </summary>
        [JsonProperty("datetime")]
        public string?  Datetime { get; set; }
        /// <summary>
        ///  DatetimeMin For a date range EDD format, the date and time for the lower end of the range.
        /// </summary>
        [JsonProperty("datetime_min")]
        public string?  DatetimeMin { get; set; }
        /// <summary>
        ///  DatetimeMax For a date range EDD format, the date and time for the upper end of the range.
        /// </summary>
        [JsonProperty("datetime_max")]
        public string?  DatetimeMax { get; set; }
        /// <summary>
        ///  ReviseReason Explains the reason for a change to the latest_estimated_delivery. This string will only have a value if:1. The source for the latest EDD is AfterShip EDD. 2. The reason for the change is known.For a comprehensive list of reasons, please refer to .
        /// </summary>
        [JsonProperty("revise_reason")]
        public string?  ReviseReason { get; set; }
        public TrackingLatestEstimatedDelivery()
        {
        }
    }
}
