/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// Description
    /// </summary>
    public class GetCouriersOptions : BaseOptions
    {
        public GetCouriersOptions()
        {
        }

        public bool? Active { get; set; }
        public string? Slug { get; set; }

        override public List<KeyValuePair<string, string>> GetQueryParams()
        {
            var p = new List<KeyValuePair<string, string>>();
            if (Active != null)
            {
                p.Add(new KeyValuePair<string, string>("active", Active.ToString().ToLower()));
            }
            if (Slug != null)
            {
                p.Add(new KeyValuePair<string, string>("slug", Slug));
            }
            return p;
        }
    }
    /// <summary>
    /// Description
    /// </summary>
    public class DetectCourierOptions : BaseOptions
    {
        public DetectCourierOptions()
        {
        }


        public DetectCourierRequest DetectCourierRequest { get; set; }

        override public string GetBody()
        {
            string body = null;

            if (DetectCourierRequest != null)
            {
                body = BaseResourceService.ToJson(DetectCourierRequest);
            }
            return body;
        }
    }
}
