/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Net.Http;

namespace AfterShipTracking
{
    public class CourierService : BaseResourceService
    {
        IHttpClient HttpClient;

        public CourierService(IHttpClient httpClient)
        {
            this.HttpClient = httpClient;
        }

        public GetCouriersResponse GetCouriers( GetCouriersOptions? options = null)
        {
            string path = $"/tracking/2026-07/couriers";
            Request request = new Request(
                HttpMethod.Get,
                path,
                options
            );

            var response = this.HttpClient.MakeRequest(request);
            GetCouriersResponseData responseData = ProcessData<GetCouriersResponseData>(response);

            GetCouriersResponse result = new GetCouriersResponse();
            result.ResponseHeader = response.Headers;
            result.Data = responseData;

            return result;
        }
        public DetectCourierResponse DetectCourier( DetectCourierOptions? options = null)
        {
            string path = $"/tracking/2026-07/couriers/detect";
            Request request = new Request(
                HttpMethod.Post,
                path,
                options
            );

            var response = this.HttpClient.MakeRequest(request);
            DetectCourierResponseData responseData = ProcessData<DetectCourierResponseData>(response);

            DetectCourierResponse result = new DetectCourierResponse();
            result.ResponseHeader = response.Headers;
            result.Data = responseData;

            return result;
        }
    }
}

