/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Net.Http;

namespace AfterShipTracking
{
    public class EstimatedDeliveryDateService : BaseResourceService
    {
        IHttpClient HttpClient;

        public EstimatedDeliveryDateService(IHttpClient httpClient)
        {
            this.HttpClient = httpClient;
        }

        public PredictResponse Predict( PredictOptions? options = null)
        {
            string path = $"/tracking/2026-01/estimated-delivery-date/predict";
            Request request = new Request(
                HttpMethod.Post,
                path,
                options
            );

            var response = this.HttpClient.MakeRequest(request);
            EstimatedDeliveryDateResponse responseData = ProcessData<EstimatedDeliveryDateResponse>(response);

            PredictResponse result = new PredictResponse();
            result.ResponseHeader = response.Headers;
            result.Data = responseData;

            return result;
        }
        public PredictBatchResponse PredictBatch( PredictBatchOptions? options = null)
        {
            string path = $"/tracking/2026-01/estimated-delivery-date/predict-batch";
            Request request = new Request(
                HttpMethod.Post,
                path,
                options
            );

            var response = this.HttpClient.MakeRequest(request);
            PredictBatchResponseData responseData = ProcessData<PredictBatchResponseData>(response);

            PredictBatchResponse result = new PredictBatchResponse();
            result.ResponseHeader = response.Headers;
            result.Data = responseData;

            return result;
        }
    }
}

