/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System.Collections.Generic;

namespace AfterShipTracking
{
    public class ErrorCode
    {
        public const string INVALID_API_KEY = "INVALID_API_KEY";
        public const string INVALID_OPTION = "INVALID_OPTION";
        public const string BAD_REQUEST = "BAD_REQUEST";
        public const string RATE_LIMIT_EXCEED = "RATE_LIMIT_EXCEED";
        public const string TIMED_OUT = "TIMED_OUT";
        public const string UNKNOWN_ERROR = "UNKNOWN_ERROR";
        public const string INVALID_REQUEST = "INVALID_REQUEST";
        public const string INVALID_JSON = "INVALID_JSON";
        public const string TRACKING_ALREADY_EXIST = "TRACKING_ALREADY_EXIST";
        public const string TRACKING_DOES_NOT_EXIST = "TRACKING_DOES_NOT_EXIST";
        public const string TRACKING_NUMBER_INVALID = "TRACKING_NUMBER_INVALID";
        public const string TRACKING_REQUIRED = "TRACKING_REQUIRED";
        public const string TRACKING_NUMBER_REQUIRED = "TRACKING_NUMBER_REQUIRED";
        public const string VALUE_INVALID = "VALUE_INVALID";
        public const string VALUE_REQUIRED = "VALUE_REQUIRED";
        public const string SLUG_INVALID = "SLUG_INVALID";
        public const string MISSING_OR_INVALID_REQUIRED_FIELD = "MISSING_OR_INVALID_REQUIRED_FIELD";
        public const string BAD_COURIER = "BAD_COURIER";
        public const string INACTIVE_RETRACK_NOT_ALLOWED = "INACTIVE_RETRACK_NOT_ALLOWED";
        public const string NOTIFICATION_REQUIRED = "NOTIFICATION_REQUIRED";
        public const string ID_INVALID = "ID_INVALID";
        public const string RETRACK_ONCE_ALLOWED = "RETRACK_ONCE_ALLOWED";
        public const string TRACKING_NUMBER_FORMAT_INVALID = "TRACKING_NUMBER_FORMAT_INVALID";
        public const string API_KEY_INVALID = "API_KEY_INVALID";
        public const string REQUEST_NOT_ALLOWED = "REQUEST_NOT_ALLOWED";
        public const string NOT_FOUND = "NOT_FOUND";
        public const string TOO_MANY_REQUEST = "TOO_MANY_REQUEST";
        public const string INTERNAL_ERROR = "INTERNAL_ERROR";

        private static Dictionary<int, string> errorMap = new Dictionary<int, string>
        {
            { 400, INVALID_REQUEST },
            { 4001, INVALID_JSON },
            { 4003, TRACKING_ALREADY_EXIST },
            { 4004, TRACKING_DOES_NOT_EXIST },
            { 4005, TRACKING_NUMBER_INVALID },
            { 4006, TRACKING_REQUIRED },
            { 4007, TRACKING_NUMBER_REQUIRED },
            { 4008, VALUE_INVALID },
            { 4009, VALUE_REQUIRED },
            { 4010, SLUG_INVALID },
            { 4011, MISSING_OR_INVALID_REQUIRED_FIELD },
            { 4012, BAD_COURIER },
            { 4013, INACTIVE_RETRACK_NOT_ALLOWED },
            { 4014, NOTIFICATION_REQUIRED },
            { 4015, ID_INVALID },
            { 4016, RETRACK_ONCE_ALLOWED },
            { 4017, TRACKING_NUMBER_FORMAT_INVALID },
            { 401, API_KEY_INVALID },
            { 403, REQUEST_NOT_ALLOWED },
            { 404, NOT_FOUND },
            { 429, TOO_MANY_REQUEST },
            { 500, INTERNAL_ERROR },
            { 502, INTERNAL_ERROR },
            { 503, INTERNAL_ERROR },
            { 504, INTERNAL_ERROR },
        };

        public static AfterShipError GenAPIError(int statusCode, int metaCode, string responseBody = null, string message = null, object responseHeader = null)
        {
            string errorCode = LocateErrorCode(metaCode, statusCode);
            return GenError(errorCode, statusCode, metaCode, responseBody, message, responseHeader);
        }

        public static AfterShipError GenSDKError(string errorCode, string message = null)
        {
            return GenError(errorCode, null, null, null, message);
        }

        public static AfterShipError GenError(string errorCode, int? statusCode, int? metaCode, string responseBody = null, string message = null, object responseHeader = null)
        {
            if (string.IsNullOrEmpty(message))
            {
                message = "Unknown error";
            }
            return new AfterShipError(message, errorCode, statusCode, metaCode, responseBody, responseHeader);
        }

        private static string LocateErrorCode(int metaCode, int statusCode)
        {
            if (errorMap.ContainsKey(metaCode))
            {
                return errorMap[metaCode];
            }
            if (statusCode >= 400 && statusCode < 500)
            {
                return BAD_REQUEST;
            }
            return UNKNOWN_ERROR;
        }
    }
}
