/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System.Collections.Generic;
using Newtonsoft.Json;

namespace AfterShipTracking
{
    /// <summary>
    /// Description
    /// </summary>
    public class GetCourierConnectionsOptions : BaseOptions
    {
        public  GetCourierConnectionsOptions()
        {
        }

        public string? CourierSlug { get; set; }
        public string? Cursor { get; set; }
        public string? Limit { get; set; }

        override public List<KeyValuePair<string, string>> GetQueryParams()
        {
            var p = new List<KeyValuePair<string, string>>();
            if (CourierSlug != null) {
                p.Add(new KeyValuePair<string, string>("courier_slug", CourierSlug));
            }
            if (Cursor != null) {
                p.Add(new KeyValuePair<string, string>("cursor", Cursor));
            }
            if (Limit != null) {
                p.Add(new KeyValuePair<string, string>("limit", Limit));
            }
            return p;
        }
    }
    /// <summary>
    /// Description
    /// </summary>
    public class PostCourierConnectionsOptions : BaseOptions
    {
        public  PostCourierConnectionsOptions()
        {
        }


        public PostCourierConnectionsRequest PostCourierConnectionsRequest { get; set; }

        override public string GetBody()
        {
            string body = null;

            if ( PostCourierConnectionsRequest != null)
            {
                body = BaseResourceService.ToJson(PostCourierConnectionsRequest);
            }
            return body;
        }
    }
    /// <summary>
    /// Description
    /// </summary>
    public class GetCourierConnectionsByIdOptions : BaseOptions
    {
        public  GetCourierConnectionsByIdOptions()
        {
        }


    }
    /// <summary>
    /// Description
    /// </summary>
    public class PutCourierConnectionsByIdOptions : BaseOptions
    {
        public  PutCourierConnectionsByIdOptions()
        {
        }


        public PutCourierConnectionsByIdRequest PutCourierConnectionsByIdRequest { get; set; }

        override public string GetBody()
        {
            string body = null;

            if ( PutCourierConnectionsByIdRequest != null)
            {
                body = BaseResourceService.ToJson(PutCourierConnectionsByIdRequest);
            }
            return body;
        }
    }
    /// <summary>
    /// Description
    /// </summary>
    public class DeleteCourierConnectionsByIdOptions : BaseOptions
    {
        public  DeleteCourierConnectionsByIdOptions()
        {
        }


    }
}
