/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
using System;
using System.Net.Http;

namespace AfterShipTracking
{
    public class CourierConnectionService : BaseResourceService
    {
        IHttpClient HttpClient;

        public CourierConnectionService(IHttpClient httpClient)
        {
            this.HttpClient = httpClient;
        }

        public GetCourierConnectionsResponse GetCourierConnections( GetCourierConnectionsOptions? options = null)
        {
            string path = $"/tracking/2026-07/courier-connections";
            Request request = new Request(
                HttpMethod.Get,
                path,
                options
            );

            var response = this.HttpClient.MakeRequest(request);
            GetCourierConnectionsResponseData responseData = ProcessData<GetCourierConnectionsResponseData>(response);

            GetCourierConnectionsResponse result = new GetCourierConnectionsResponse();
            result.ResponseHeader = response.Headers;
            result.Data = responseData;

            return result;
        }
        public PostCourierConnectionsResponse PostCourierConnections( PostCourierConnectionsOptions? options = null)
        {
            string path = $"/tracking/2026-07/courier-connections";
            Request request = new Request(
                HttpMethod.Post,
                path,
                options
            );

            var response = this.HttpClient.MakeRequest(request);
            CourierConnection responseData = ProcessData<CourierConnection>(response);

            PostCourierConnectionsResponse result = new PostCourierConnectionsResponse();
            result.ResponseHeader = response.Headers;
            result.Data = responseData;

            return result;
        }
        public GetCourierConnectionsByIdResponse GetCourierConnectionsById(string id,  GetCourierConnectionsByIdOptions? options = null)
        {
            string path = $"/tracking/2026-07/courier-connections/{id}";
            if (string.IsNullOrEmpty(id))
            {
               throw ErrorCode.GenSDKError(ErrorCode.BAD_REQUEST, "Invalid request"+": `id` is invalid");
            }
            Request request = new Request(
                HttpMethod.Get,
                path,
                options
            );

            var response = this.HttpClient.MakeRequest(request);
            CourierConnection responseData = ProcessData<CourierConnection>(response);

            GetCourierConnectionsByIdResponse result = new GetCourierConnectionsByIdResponse();
            result.ResponseHeader = response.Headers;
            result.Data = responseData;

            return result;
        }
        public PutCourierConnectionsByIdResponse PutCourierConnectionsById(string id,  PutCourierConnectionsByIdOptions? options = null)
        {
            string path = $"/tracking/2026-07/courier-connections/{id}";
            if (string.IsNullOrEmpty(id))
            {
               throw ErrorCode.GenSDKError(ErrorCode.BAD_REQUEST, "Invalid request"+": `id` is invalid");
            }
            Request request = new Request(
                HttpMethod.Patch,
                path,
                options
            );

            var response = this.HttpClient.MakeRequest(request);
            CourierConnection responseData = ProcessData<CourierConnection>(response);

            PutCourierConnectionsByIdResponse result = new PutCourierConnectionsByIdResponse();
            result.ResponseHeader = response.Headers;
            result.Data = responseData;

            return result;
        }
        public DeleteCourierConnectionsByIdResponse DeleteCourierConnectionsById(string id,  DeleteCourierConnectionsByIdOptions? options = null)
        {
            string path = $"/tracking/2026-07/courier-connections/{id}";
            if (string.IsNullOrEmpty(id))
            {
               throw ErrorCode.GenSDKError(ErrorCode.BAD_REQUEST, "Invalid request"+": `id` is invalid");
            }
            Request request = new Request(
                HttpMethod.Delete,
                path,
                options
            );

            var response = this.HttpClient.MakeRequest(request);
            CourierConnection responseData = ProcessData<CourierConnection>(response);

            DeleteCourierConnectionsByIdResponse result = new DeleteCourierConnectionsByIdResponse();
            result.ResponseHeader = response.Headers;
            result.Data = responseData;

            return result;
        }
    }
}

